#!/bin/bash

export AWS_ACCESS_KEY_ID=ASIAIASCOKLASFUPAOLA
export AWS_SECRET_ACCESS_KEY=SDjrhJlx2MeqkCRM4NjNvzAMlzE6iPETNEd9hnmo
export AWS_SECURITY_TOKEN=AQoDYXdzEGcakALtBHJBNHg62M0d0NZlgwqOdw8qUJVEwrwDD9AIXTLOs7E9lh8CghxGYpwVKBq/37sfY9tO2npVEua9YdWutFrpJsHoJStgfkKCi0pKszwRxfyuRdhMGX5WvllIaQ9EOWrbNh+UDApgp7232mTweaoSG8GcwZ1yQiTtNDbyHQZnNkS8nolYLK5jGuUIqA52n+UmvUuZAKO8SeAqwtVrbvChPjQfXj24tOEboHamhEzMd57QNmwUj9ZnAtNcnwJWejwiO2Vzz+EwZ/Pw3ApbSd9XY1NMA7VjKiY8zpSv47j5huWHg/qXHhk3tTLQRRc3eEiBZerWc/aEifNIptXxpw8AZ16lalzwDpSOmcp2AqGdnSDGxLi2BQ==


aws s3 ls s3://klab-jobs

#aws ec2 describe-instances --region us-west-1
